### ISSUE TITLE
佩服

### ISSUE THREAD

**Issue by zcker** [jingyuexing/Ebook#2]
兄弟涉猎广泛啊，数学及玄学，看到这么多玄学书籍，请问兄弟是否相信宿命论？为什么会收集玄学的书目呢？

**Comment by jingyuexing** [comment]
> 兄弟涉猎广泛啊，数学及玄学，看到这么多玄学书籍，请问兄弟是否相信宿命论？为什么会收集玄学的书目呢？

只是为了写故事特地去查的资料,我是一个唯物主义者

**Comment by jingyuexing** [comment]
> 兄弟涉猎广泛啊，数学及玄学，看到这么多玄学书籍，请问兄弟是否相信宿命论？为什么会收集玄学的书目呢？

从哪儿看到的这个仓库啊, 在github搜的还是哪个链接？
